export default function Head() {
  return (
    <>
      <title>Certified Web 3.0 and Metaverse Developer: A Nationwide Program in Karachi, Lahore, Islamabad, and Peshawar</title>
      <meta name="title" content="Certified Web 3.0 and Metaverse Developer: A Nationwide Program in Karachi, Lahore, Islamabad, and Peshawar" />
      <meta name="locale" content="en_US" />
      <meta name="description" content="Getting Ready for the Next Generation and Future of the Internet - Join a 13 Trillion Dollar Industry with 5 Billion Users" />          
      <meta name="url" content="https://www.panaverse.co/" />
      <meta name="site_name" content="Panaverse" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="canonical" href="https://www.panaverse.co/" />
      <link rel="icon" href="/logo.ico" />       
    </>
  )
}
